- name: Configure application servers
  hosts: all
  gather_facts: false
  connection: amazon.aws.aws_ssm

  tasks:
    - name: Prove Ansible ran
      ansible.builtin.shell: echo "ANSIBLE VIA SSM WORKING"

