- name: Configure application servers
  hosts: all
  connection: community.aws.aws_ssm
  gather_facts: false
  become: true

  tasks:
    - name: Test SSM connectivity
      ansible.builtin.command: whoami
